# Generated by Django 4.2.17 on 2024-12-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Victims',
                'verbose_name_plural': 'Victims',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
