# Generated by Django 4.2.17 on 2024-12-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaccaunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='victims',
            options={'managed': True, 'verbose_name': 'Victim', 'verbose_name_plural': 'Victims'},
        ),
    ]
